name = "filewxchat"
main = "worker/index.js"
compatibility_date = "2025-07-03"

# 静态资源配置 - 使用正确的格式
[assets]
directory = "./public"
binding = "ASSETS"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "fliechat"
database_id = "daf7a300-04a6-4a95-94c6-7c37ca22ecc5"

# R2 存储桶绑定
[[r2_buckets]]
binding = "R2"
bucket_name = "fliechat"

# 环境变量配置（用于鉴权）
[vars]
# 访问密码（明文，直接在Cloudflare Workers控制台配置）
ACCESS_PASSWORD = "1925985335"
# JWT密钥（用于会话管理）
JWT_SECRET = "8738ddab-3233-403d-928e-c465c2ed499d"
# 会话过期时间（小时）
SESSION_EXPIRE_HOURS = "24"
# 最大登录尝试次数
MAX_LOGIN_ATTEMPTS = "5"


